Branch tina
auxfuse/hackathon-git-labs pull request #224
Opened 2023-02-23 08:58 UTC by Tinks18

# Hackathon Git Labs Project PR 🎉🎉

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
- Json file changes to community.json and emoji.json files
{
        "name": "Tina",
        "course_start": "2022",
        "course_stage": "Student",
        "favorite_language": "JS",
        "currently_learning": "Full Stack Frameworks - Django"
    }

## Breaking changes
-  'None'

## Screenshots
- 'None'

2023-03-11 08:40 UTC, andrewdempsey2018 requested changes
Hi @Tinks18 This is fantastic! I love the additional ascii emoji (they should not be allowed to die IMHO!!) I'd imagine we cannot accept those additions to the main index page would you agree @auxfuse

2023-03-13 07:08 UTC, andrewdempsey2018 approved these changes

2023-03-13 17:19 UTC, Tinks18 reviewed
finally finished.

2023-03-13 18:52 UTC, andrewdempsey2018 approved these changes
Awesome @Tinks18

2023-03-13 18:52 UTC, merged